In [1]:
#importing libs
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier

In [2]:
#Creating the dataframe
df = pd.read_csv("C:/Users/facla/Documents/CursoPython/Cap11/pima-data.csv")

In [3]:
df.shape

(768, 10)

In [4]:
df.head(5)

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,skin,diabetes
0,6,148,72,35,0,33.6,0.627,50,1.3780,True
1,1,85,66,29,0,26.6,0.351,31,1.1426,False
2,8,183,64,0,0,23.3,0.672,32,0.0000,True
3,1,89,66,23,94,28.1,0.167,21,0.9062,False
4,0,137,40,35,168,43.1,2.288,33,1.3790,True

In [5]:
#Checking for null values
df.isnull().values.any()

False

In [6]:
#Adicionar linha vazia para teste
#df = df.append(pd.Series(), ignore_index=True)

In [7]:
df.isnull()

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,skin,diabetes
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
763,False,False,False,False,False,False,False,False,False,False
764,False,False,False,False,False,False,False,False,False,False
765,False,False,False,False,False,False,False,False,False,False
766,False,False,False,False,False,False,False,False,False,False
767,False,False,False,False,False,False,False,False,False,False

In [8]:
#Remoce linha vazia
#if df.isnull().values.any():
 #   df = df.dropna()

In [9]:
df.isnull()

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,skin,diabetes
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
763,False,False,False,False,False,False,False,False,False,False
764,False,False,False,False,False,False,False,False,False,False
765,False,False,False,False,False,False,False,False,False,False
766,False,False,False,False,False,False,False,False,False,False
767,False,False,False,False,False,False,False,False,False,False

In [10]:
pd.crosstab(index=df['diabetes'], columns='count')

col_0     count
diabetes
False       500
True        268

In [11]:
import sklearn as sk
from sklearn.model_selection import train_test_split
X = df.values
Y = df["diabetes"].values

In [25]:
df_train, df_test, y_train, y_teste = train_test_split(df, Y, test_size=0.25, random_state = 42, shuffle = True)

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,skin,diabetes
357,13,129,0,30,0,39.9,0.569,44,1.1820,True
73,4,129,86,20,270,35.1,0.231,23,0.7880,False
352,3,61,82,28,0,34.4,0.243,46,1.1032,False
497,2,81,72,15,76,30.1,0.547,25,0.5910,False
145,0,102,75,23,0,0.0,0.572,21,0.9062,False
...,...,...,...,...,...,...,...,...,...,...
71,5,139,64,35,140,28.6,0.411,26,1.3790,False
106,1,96,122,0,0,22.4,0.207,27,0.0000,False
270,10,101,86,37,0,45.6,1.136,38,1.4578,True
435,0,141,0,0,0,42.4,0.205,29,0.0000,True
102,0,125,96,0,0,22.5,0.262,21,0.0000,False

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,skin,diabetes
668,6,98,58,33,190,34.0,0.430,43,1.3002,False
324,2,112,75,32,0,35.7,0.148,21,1.2608,False
624,2,108,64,0,0,30.8,0.158,21,0.0000,False
690,8,107,80,0,0,24.6,0.856,34,0.0000,False
473,7,136,90,0,0,29.9,0.210,50,0.0000,False
...,...,...,...,...,...,...,...,...,...,...
554,1,84,64,23,115,36.9,0.471,28,0.9062,False
319,6,194,78,0,0,23.5,0.129,59,0.0000,True
594,6,123,72,45,230,33.6,0.733,34,1.7730,False
6,3,78,50,32,88,31.0,0.248,26,1.2608,True
615,3,106,72,0,0,25.8,0.207,27,0.0000,False

In [32]:

df_test.drop('diabetes', inplace=True, axis=1)
df_train.drop('diabetes', inplace=True, axis=1)

In [16]:
features = ["num_preg",	"glucose_conc",	"diastolic_bp",	"thickness", "insulin",	"bmi", "diab_pred", "age", "skin"]
X = pd.get_dummies(df_train[features])
X_test = pd.get_dummies(df_test[features])

In [36]:
#Primeiro Modelo (RandomForest)
model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)
model.fit(X, y_train)
predictions = model.predict(X_test)

In [37]:
output = pd.DataFrame({'PersonId': df_test.index, 'diabetes': predictions})
output.to_csv('submission.csv', index=False)

In [38]:
from sklearn import metrics
print("{0:.4f}".format(metrics.accuracy_score(y_teste, predictions)))

0.7656

In [39]:
#Segundo modelo (GaussianNB() / naive Bayes)
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred_gnb = gnb.fit(df_train, y_train).predict(df_test)
print("{0:.4f}".format(metrics.accuracy_score(y_teste, y_pred_gnb)))

0.7240

GaussianNB()

TypeError: Expected sequence or array-like, got <class 'sklearn.naive_bayes.GaussianNB'>